### ISSUE TITLE
Size of day2

### ISSUE THREAD

**Issue by dcferreira** [davidbp/lxmls-notebooks#7]
Hi,

In my laptop, opening day2 in jupyter throws a timeout error while opening. I split it locally in multiple files, and was able to open it then.

I could open a pull request for this, but I have a naming problem: day2 is big and can be split into like 5 files, since there are multiple exercises distributed throughout the day. The way I did it, I got files day2/exercise_1.ipynb, day2/exercise_2.ipynb, day2/exercise_3_4.ipynb, etc. However, for example day4 doesn't have this problem, and the exercises are all bunched together, so it's impossible to split them in a reasonable way.

In my local repo I started doing a split for each day (so each day is a directory with multiple notebooks), but then realized it doesn't make sense to split day4, and so currently is a directory with a single file (so it could as easily be just one file instead of a directory). However, having mixed files and directories also doesn't look like a good idea.

Any good suggestion for this? The original problem is that the day2 notebook is too big.

**Comment by bastings** [comment]
Hi, I think we should go for 1 directory per day. It's fine for day 4 to have a single file there in my opinion. 
I'd like to merge the pull request for day 4 that is still open though.

**Comment by dcferreira** [comment]
I can make a pull request for that then (will do one a day, so that it is easier to merge).

**Comment by bastings** [comment]
Alright thanks! Note that I just updated day4.
